### ISSUE TITLE
关于那题文件上传zip解压

### ISSUE THREAD

**Issue by Hwwg** [Jason1314Zhang/BUUCTF-WP#17]
他解压出来的文件不是还会经过一次check_dir()函数的检查吗，穿越目录后就可以逃过检查吗

**Comment by SuperJason6** [comment]
文件已经穿越到解压目录的上层，check_dir()只检查解压目录内的文件后缀

**Comment by Hwwg** [comment]
感谢师傅

**Comment by Hwwg** [comment]
> 
> 
> 文件已经穿越到解压目录的上层，check_dir()只检查解压目录内的文件后缀

感谢师傅
